routes/schedule.py
from flask import jsonify, request, Blueprint, render_template
from .models import db, CityCounty 
from dotenv import load_dotenv
import os

load_dotenv()
key = os.getenv("choakey")

schedule_bp = Blueprint("schedule", __name__, url_prefix="/schedule")

@schedule_bp.route("/", methods=["GET"])
def main():
    destinations = db.session.query(
        CityCounty.sido,
        CityCounty.sigungu,
        db.func.max(CityCounty.latitude).label('latitude'),
        db.func.max(CityCounty.longitude).label('longitude'),
        db.func.max(CityCounty.adm_code).label('adm_code')
    ).group_by(
        CityCounty.sido,
        CityCounty.sigungu
    ).all()
    
    processed_destinations = [
        {
            'city_name': f"{d.sido} {d.sigungu}", 
            'sido': d.sido,                       
            'sigungu': d.sigungu,                
            'adm_code': d.adm_code,
            'latitude': d.latitude,
            'longitude': d.longitude,
            'data_destination': f"{d.sido} {d.sigungu}" 
        } for d in destinations
    ]
            
    return render_template("schedule/schedule_main.html", destinations=processed_destinations)

@schedule_bp.route("/view", methods=["GET"])
def view():
    return render_template("schedule/schedule_view.html", choakey=key)

@schedule_bp.route("/list", methods=["GET"])
def list():
    return render_template("schedule/schedule_list.html")

templates/schedule/schedule_list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TripMocha</title>
  {% include 'config/config.html' %}
  <link rel="stylesheet" href="{{url_for('static', filename='css/schedule_list.css')}}">
</head>

<body>
    <div id="wrap">
        {% include 'config/header.html' %}
        <div id="container">
            <!-- 작업영역 -->
            <table>
                <tr>
                    <td><button class="new-trip-button"><a href="{{ url_for('schedule.main') }}"> + 새 여행
                                만들기</a></button></td>
                </tr>
            </table>

            {% if trips %}
            {% for trip in trips %}
            <div class="trip-item">
                <a href="{{ url_for('schedule.view', trip_id=trip.id) }}" class="trip-link-wrapper">
                    <table>
                        <tr>
                            <td rowspan="2" style="width: 105px;"><img src="{{ trip.image_url }}"
                                    alt="{{ trip.title }} 이미지" class="trip-image"></td>
                            <td style="width: calc(100% - 150px);">
                                <div class="trip-title">{{ trip.title }}</div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="trip-info">{{ trip.start_date }} → {{ trip.end_date }} 📍 {{ trip.location
                                    }}</div>
                                <div class="trip-tags">
                                    {% for tag in trip.tags.split(',') %}
                                    <span>#{{ tag | trim }}</span>
                                    {% endfor %}
                                </div>
                            </td>
                            <td></td>
                        </tr>
                    </table>
                </a>
                <div>
                    <a href="#">수정</a> | 삭제
                </div>
            </div>
            {% endfor %}

            {% else %}
            <div class="trip-item">
                <a class="trip-link-wrapper">
                    <table>
                        <tr>
                            <td rowspan="2" style="width: 105px;"></td>
                            <td style="width: calc(100% - 150px);">
                                <div class="trip-title">군산시여행</div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="trip-info">2025-12-5 → 2025-12-6 📍 군산시</div>
                                <div class="trip-tags">
                                    <span>#맛집</span>
                                    <span>#체험</span>
                                    <span>#축제</span>
                                </div>
                            </td>
                            <td></td>
                        </tr>
                    </table>
                </a>
            </div>    
                <div class="trip-item">
                    <table id="no-travle">
                        <tr>
                            <td>
                                <img src="{{ url_for('static', filename='img/nono.png') }}">
                            </td>
                        </tr>
                    </table>
                </div>

                {% endif %}

                <!-- 작업영역 -->
            </div>
            {% include 'config/footer.html' %}
        </div>
</body>

</html>

templates/schedule/schedule_main.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TripMocha</title>
    <style>

    </style>
    <!-- css -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/schedule_main.css')}}">

    <!-- stylesheet -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
    <!-- js -->

    <script type=text/javascript src="{{url_for('static', filename='js/jquery-3.7.1.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    <script type=text/javascript src="{{url_for('static', filename='js/main.js') }}"></script>
    <script type=text/javascript src="{{url_for('static', filename='js/schedule_main.js') }}"></script>

    <!-- etc -->
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1" /> -->
</head>

<body>
    <div id="wrap">
        {% include 'config/header.html' %}
        <div id="container">
            <!-- 작업영역 -->
            <div class="h22-and-input">
                <div class="travel-name-outer-container"></div>
                <div class="mytravel">
                    <h1>나의 여행 만들기</h1>
                </div>
                <!-- <div class="input-wrapper">
                    <div class="input-container"> 
                        <input type="text" class="search-input" placeholder="여행 제목을 만들어주세요.  ex:부산에서 여름휴가!">
                        <button class="confirm-button">저장</button>
                    </div>
                </div> -->
            </div>

            <h2 style="margin-top: 40px;"></h2>

            <div id="wrap">
                <div class="top-search-bar">
                    <div class="top-search-item" id="destinationItem">
                        <span class="search-label">여행지</span>
                        <span id="searchPlaceholder" class="sub-label">여행지 검색</span>
    
                        <input type="text" id="destinationSearchInput" style="display: none;" /> 

                        <span class="display-group">
                            <span class="selected-province"></span>
                            <span class="selected-city"></span>
                        </span>

                        <div class="dropdown-content" id="destinationDropdown">
                            {% for dest in destinations %}
                            <div class="destination-item" data-city="{{ dest.city_name }}"
                                data-code="{{ dest.adm_code }}" data-lat="{{ dest.latitude }}"
                                data-lng="{{ dest.longitude }}" data-destination="{{ dest.city_name }}">
                                <div class="dest-info">
                                    <div class="dest-name">{{ dest.sigungu }}</div>
                                    <div class="dest-sido">{{ dest.sido }}</div>

                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="top-search-item" id="dateItem">
                        <span class="search-label" id="dateDisplay">날짜</span>
                        <span class="sub-label">날짜 추가</span>
                        <span class="display-group">
                            <span class="selected-dates"></span>
                            <span class="selected-duration"></span>
                        </span>
                        <div class="dropdown-content" id="calendarDropdown">
                            <div class="calendar-col">
                                <div class="calendar-header">
                                    <span class="prev-month">&lt;</span>
                                    <span id="month1">2025년 11월</span>
                                    <span></span>
                                </div>
                                <div id="calendarContainer1"></div>
                            </div>
                            <div class="calendar-col">
                                <div class="calendar-header">
                                    <span></span> <span id="month2">2025년 12월</span>
                                    <span class="next-month">&gt;</span>
                                </div>
                                <div id="calendarContainer2"></div>
                            </div>

                            <div class="calendar-footer">
                                <button class="reset-btn">지우기</button>
                                <button class="apply-btn">적용</button>
                            </div>
                        </div>
                    </div>

                    <div class="top-search-item" id="tourTypeItem">
                        <span class="search-label">인원</span>
                        <span class="sub-label">인원 선택</span>
                        <span class="display-group">
                            <span class="selected-personnel-name"></span>
                            <span class="selected-personnel-count"></span>
                        </span>
                        <div class="dropdown-content" id="tourDropdown">
                            <div class="tour-tabs">
                                <div class="tour-tab active" data-type="solo">1인</div>
                                <div class="tour-tab" data-type="couple">커플</div>
                                <div class="tour-tab" data-type="couple">친구</div>
                            </div>
                            <div class="tour-tabs">
                                <div class="tour-tab" data-type="couple">가족</div>
                                <div class="tour-tab" data-type="couple">아이동반</div>
                                <div class="tour-tab" data-type="couple">부모님동반</div>
                            </div>

                            <div class="tour-type-item">
                                <span>여행자</span>
                                <div class="count-controls">
                                    <div class="count-btn minus-btn" data-target="friend">-</div>
                                    <div class="count-number" id="friendCount">0</div>
                                    <div class="count-btn plus-btn" data-target="friend">+</div>
                                </div>
                            </div>

                            <div class="calendar-footer">
                                <button class="reset-btn">지우기</button>
                                <button class="apply-btn">적용</button>
                            </div>
                        </div>
                    </div>

                    <button class="search-button">추가</button>

                </div>

                <div class="h22-and-input">
                    <h2>여행 테마</h2>
                    <p class="input-wrapper2">원하는 여행 테마 2가지 선택해주세요. (최대 4개 선택)

                </div>
                <table id="theme-selection-table">
                    <tr>
                        <td class="theme-icon-container select-btn" data-theme="ai">
                            <div class="theme-icon">📸<div class="selection-overlay">
                                    <span class="check-icon">✔</span>
                                </div>
                            </div><br>AI 추천
                        </td>
                        <td class="theme-icon-container select-btn" data-theme="mountain">
                            <div class="theme-icon">⛰️<div class="selection-overlay">
                                    <span class="check-icon">✔</span>
                                </div>
                            </div><br>산
                        </td>
                        <td class="theme-icon-container select-btn" data-theme="sea">
                            <div class="theme-icon">🏖️<div class="selection-overlay">
                                    <span class="check-icon">✔</span>
                                </div>
                            </div><br>바다
                        </td>
                        <td class="theme-icon-container select-btn" data-theme="indoor">
                            <div class="theme-icon">🏠<div class="selection-overlay">
                                    <span class="check-icon">✔</span>
                                </div>
                            </div><br>실내
                        </td>
                        <td class="theme-icon-container select-btn" data-theme="activity">
                            <div class="theme-icon">🧗<div class="selection-overlay">
                                    <span class="check-icon">✔</span>
                                </div>
                            </div><br>액티비티
                        </td>
                        <td class="theme-icon-container select-btn" data-theme="experience">
                            <div class="theme-icon">🧑‍🎨<div class="selection-overlay">
                                    <span class="check-icon">✔</span>
                                </div>
                            </div><br>체험
                        </td>
                    </tr>
                    <tr>
                        <td class="theme-icon-container select-btn" data-theme="themepark">
                            <div class="theme-icon">🎡<div class="selection-overlay">
                                    <span class="check-icon">✔</span>
                                </div>
                            </div><br>테마파크
                        </td>
                        <td class="theme-icon-container select-btn" data-theme="market">
                            <div class="theme-icon">🛍️<div class="selection-overlay">
                                    <span class="check-icon">✔</span>
                                </div>
                            </div><br>전통시장
                        </td>
                        <td class="theme-icon-container select-btn" data-theme="food">
                            <div class="theme-icon">🍽️<div class="selection-overlay">
                                    <span class="check-icon">✔</span>
                                </div>
                            </div><br>맛집
                        </td>
                        <td class="theme-icon-container select-btn" data-theme="festival">
                            <div class="theme-icon">🎉<div class="selection-overlay">
                                    <span class="check-icon">✔</span>
                                </div>
                            </div><br>축제
                        </td>
                        <td class="theme-icon-container select-btn" data-theme="healing">
                            <div class="theme-icon">🧘<div class="selection-overlay">
                                    <span class="check-icon">✔</span>
                                </div>
                            </div><br>힐링
                        </td>
                        <td class="theme-icon-container select-btn" data-theme="photo">
                            <div class="theme-icon">📸<div class="selection-overlay">
                                    <span class="check-icon">✔</span>
                                </div>
                            </div><br>사진
                        </td>
                    </tr>
                </table>

                <p id="selection-message" style="color: red; margin-top: 10px;"></p>

                <div class="button-area">
                    <a class="button-make-travel">
                        <img src="{{ url_for('static', filename='img/travle.png') }}"></a>
                </div>
                <div id="result-area" style="margin-top: 40px;">
                </div>
                <div id="result-area">
                    <div class="trip-list-grid">
                    </div>
                    <div id="schedule-display-area">
                    </div>
                </div>

            </div>



            <!-- 작업영역 -->
        </div>
        {% include 'config/footer.html' %}
    </div>
</body>

</html>

templates/schedule/schedule_view.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TripMocha</title>
    <style>

    </style>
    <!-- css -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/schedule_view.css')}}">

    <!-- stylesheet -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
    <!-- js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"
        integrity="sha512-Z6J08Fef76tV9vX7E3x6Q5r/n4tqKx4a7aF5E3m/r8Fk6tQ3vX0f+7F1zL4zQ3z6tG6T1W0R1Z2p4aG4qA=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script type=text/javascript src="{{url_for('static', filename='js/jquery-3.7.1.js') }}"></script>

    <script type="text/javascript"
        src="https://dapi.kakao.com/v2/maps/sdk.js?appkey={{choakey}}"></script>

    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    <script type=text/javascript src="{{url_for('static', filename='js/main.js') }}"></script>

    <!-- etc -->
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1" />
</head>

<body>
    <div id="wrap">
        {% include 'config/header.html' %}
        <div id="container">
            <div class="trip-summary">
                <div class="trip-summary-left">

                    <h1 class="trip-title-main">모카님을 위한 여행코스</h1>

                    <p class="trip-dates"><strong>12월 5일 → 12월 6일</strong></p>
                    <div class="meta-info">
                        - 1인 여행<br>
                        - 여행지역 | 전주 ~ 군산<br>
                        - 총 5개 여행지 / 음식점 / 숙소 추천!
                    </div>
                </div>
                <div class="trip-summary-right">
                </div>
            </div>

            <hr style="margin: 20px 0;">

            <div class="schedule-controls">
                <h1>여행 일정</h1>

                <div class="control-buttons">
                    <button class="pdf-button" id="downloadPdfButton"
                    onclick="downloadPDF()">PDF 저장</button>
                    <a class="pdf-button" href="{{ url_for('schedule.list') }}">목록</a>
                    <a class="pdf-button" href="{{ url_for('schedule.list') }}" id="list-del-btn">삭제</a>

                </div>
            </div>

            <div class="travel-schedule-layout">
                <div class="schedule-list-area">
                    <div class="modify_cntainer">
                        <div class="schedule-day-title">Day 1 - 12월 5일 금요일</div>
                        <div id="btnwrap">
                            <a href="#" class="schedule_modify" id="popupbtn">일정편집</a>
                        </div>


                    </div>
                    <div class="timeline-item">
                        <div class="timeline-item-content">
                            <div class="details">
                                <div class="header-info">
                                    <div class="sequence">1</div>
                                    <h4>한옥마을</h4>
                                    <div class="rating">⭐ 4.5</div>
                                </div>
                                <div class="add-delete">
                                    <p>전라북도 전주시 완산구 풍남로 000</p>
                                    <button class="delete-btn hidden">삭제</button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="timeline-item">
                        <div class="timeline-item-content">
                            <div class="details">
                                <div class="header-info">
                                    <div class="sequence">2</div>
                                    <h4>한국관</h4>
                                    <div class="rating">⭐ 4.3</div>
                                </div>
                                <p>전라북도 전주시 덕진구 금암동 000</p>
                            </div>
                        </div>
                    </div>

                    <div class="timeline-item">
                        <div class="timeline-item-content">
                            <div class="details">
                                <div class="header-info">
                                    <div class="sequence">3</div>
                                    <h4>전주호텔</h4>
                                    <div class="rating">⭐ 4.5</div>
                                </div>
                                <p>전라북도 전주시 완산구 효자동 000</p>
                            </div>
                        </div>
                    </div>
                    <div class="timeline-item hidden">
                        <div class="timeline-item-content">
                            <div class="list-add" hidden>
                                <a href="#" class="add-schedule-btn" data-day="1">+ 방문지 추가</a>
                            </div>
                        </div>
                    </div>

                    <div class="schedule-day-title" style="margin-top: 3em;">Day 2 - 12월 6일 토요일</div>

                    <div class="timeline-item">
                        <div class="timeline-item-content">
                            <div class="details">
                                <div class="header-info">
                                    <div class="sequence">1</div>
                                    <h4>선유도</h4>
                                    <div class="rating">⭐ 4</div>
                                </div>
                                <p>전라북도 군산시 옥도면 선유도 </p>
                            </div>
                        </div>
                    </div>

                    <div class="timeline-item">
                        <div class="timeline-item-content">
                            <div class="details">
                                <div class="header-info">
                                    <div class="sequence">2</div>
                                    <h4>군산식당</h4>
                                    <div class="rating">⭐ 4.6</div>
                                </div>
                                <p>전라북도 군산시 옥도면 000</p>
                            </div>
                        </div>
                    </div>
                    <div class="timeline-item">
                        <div class="timeline-item-content">
                            <div class="details">
                                <div class="header-info">
                                    <div class="sequence">2</div>
                                    <h4>군산식당</h4>
                                    <div class="rating">⭐ 4.6</div>
                                </div>
                                <p>전라북도 군산시 옥도면 000</p>
                            </div>
                        </div>
                    </div>
             
                <div class="timeline-item hidden">
                        <div class="timeline-item-content">
                            <div class="list-add" hidden>
                                <a href="#" class="add-schedule-btn" data-day="1">+ 방문지 추가</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="map-section-wrapper">
                    <div id="map" class="map-container-bottom"></div>
                    <script>
                        var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
                            mapOption = {
                                center: new kakao.maps.LatLng(35.815967, 127.147255), // 지도의 중심좌표 (전주 인근)
                                level: 7 // 지도의 확대 레벨
                            };

                        // 지도를 표시할 div와 지도 옵션으로 지도를 생성합니다
                        var map = new kakao.maps.Map(mapContainer, mapOption);

                        var mapTypeControl = new kakao.maps.MapTypeControl();

                        // 지도에 컨트롤을 추가
                        map.addControl(mapTypeControl, kakao.maps.ControlPosition.TOPRIGHT);

                        // 지도 확대 축소를 제어할 수 있는 줌 컨트롤 생성
                        var zoomControl = new kakao.maps.ZoomControl();
                        map.addControl(zoomControl, kakao.maps.ControlPosition.RIGHT);


                        var marker = new kakao.maps.Marker();

                        // 타일 로드가 완료되면 지도 중심에 마커를 표시합니다
                        kakao.maps.event.addListener(map, 'tilesloaded', displayMarker);

                        function displayMarker() {
                            // 마커의 위치를 지도중심으로 설정합니다 
                            marker.setPosition(map.getCenter());
                            marker.setMap(map);

                            // kakao.maps.event.removeListener(map, 'tilesloaded', displayMarker);
                        }
                    </script>
                </div>
            </div>
        </div>
        {% include 'config/footer.html' %}
    </div>
    <div id="modalwrap">
        <div id="modalbody">
            <span id="closebtn">&times;</span>
            <p class="modal-p">방문지 추가</p>
            <br>
            <div id="modal-search-wrap">
                <div id="modal-in-search-wrap">
                    <div id="modal-search-area">
                        <form id="modalform" name="search" method="get" action="/search">
                            <div id="modal-search-input-box">
                                <input type="search" id="query" name="query" placeholder="여행지를 입력해 주세요."
                                    >
                                <i class="bi bi-search modal-search-btn"></i>
                                
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <br>
            <hr>
            <div class="modal-area-list">
                <div>풍남문</div>
                <input type="button" value="추가" class="arealist-btn">

            </div>
        </div>
    </div>
    <script type=text/javascript src="{{url_for('static', filename='js/schedule_view.js') }}"></script>
</body>

</html>