routes/basic.py
from flask import Blueprint, render_template

# basic_bp = Blueprint("basic", __name__, url_prefix="/")

# @basic_bp.route("/", methods=["GET"])
# def basic():
#   return render_template("basic/basic.html")

routes/info.py
from flask import Blueprint, g, render_template, request, redirect, url_for, session
import urllib.parse
from api_service import APIService

info_bp = Blueprint("info", __name__, url_prefix="/info")

@info_bp.route("/")
def info():
  query = ""

  #query 파라메터를 가져온다.
  url_query = request.args.get("query")
  # 값이 없으면 session에서 가져온다.
  if query is None:
    query = session.get("query", "")
  else:
    query = url_query

  # 세션에 값이 있을경우는 파라메터 값 없을 경우는 빈값을 다시 넣는다.
  session["query"] = query
  
  print("query",query)
  squery = query.strip()
  #query
  if not query or query == "전체":
    query = "전체"
    #SearchKeyword(self, keyword, contenttypeid)
    items = APIService().SearchArea()
  else:
    if( squery.startswith("#") ) :
      tag = squery[1:].split()[0]
      # 해시태그만 있고 뒤에 내용이 없을 경우
      # 전체 검색으로 간주
      print("tag",tag)
      if tag:
        items = APIService().SearchHash(tag)
      else :
        items = []
        items = APIService().SearchArea(tag)
    else:
      items = APIService().SearchKeyword(keyword=query)
  
  return render_template("info/info.html", query=query, items = items)

@info_bp.route("/<int:info_no>")
def detail(info_no):
  item = APIService().SearchCID(info_no)
  return render_template("info/detail.html", item = item)

@info_bp.route("/festival")
def festival():
  return render_template("info/festival.html")

templates/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TripMocha</title>
  {% include 'config/config.html' %}
</head>
<body>
  <div id="wrap">
    {% include 'config/header.html' %}
    <div id="container">
      <!-- 작업영역 -->
    </div>
    {% include 'config/footer.html' %}
  </div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TripMocha</title>

  {% include 'config/config.html' %}
  <link rel="stylesheet" href="{{url_for('static', filename='css/index.css')}}">
  <script type=text/javascript src="{{url_for('static', filename='js/index.js') }}"></script>

</head>
<body>
  <div id="wrap">
    {% include 'config/header.html' %}
    
    <div id="container">
      <div id="main_search_wrap">
        {% include 'config/search.html' %}
      </div>
      <div id="contents">
        <div class="thema_cont">
          <div class="cont_head">
            <h2>테마별로 찾아가기</h2>
            <p>좋아하는 테마를 선택하여 여행을 떠나보세요.</p>
          </div>
          <!-- Swiper -->
          <div class="swiper mySwiper">
            <div class="swiper-wrapper">
              <div class="swiper-slide">
                <img src="../static/img/nature.jpg">
                <a href="{{ url_for('info.info',query='자연 힐링') }}" class="card_contents">
                  <div class="card_title">
                    자연과 힐링
                  </div>
                  <div class="card_note">
                    산과 바다 등 자연 속으로 떠나는 힐링 가득한 여행
                    <span class="material-symbols-outlined arrow">arrow_right_alt</span>
                  </div>
                </a>
              </div>
              <div class="swiper-slide">
                <img src="../static/img/food.jpg">
                <a href="#" class="card_contents">
                  <div class="card_title">
                    미식탐방
                  </div>
                  <div class="card_note">
                    지역의 고유한 음식, 전통시장, 유명 맛집을 중심으로 떠나는 여행
                    <span class="material-symbols-outlined arrow">arrow_right_alt</span>
                  </div>
                </a>
              </div>
              <div class="swiper-slide">
                <img src="../static/img/history.jpg">
                <a href="#" class="card_contents">
                  <div class="card_title">
                    예술과 역사
                  </div>
                  <div class="card_note">
                    미술관, 갤러리, 박물관 등을 중심으로 문화와 역사속으로 떠나는 여행
                    <span class="material-symbols-outlined arrow">arrow_right_alt</span>
                  </div>
                </a>
              </div>
              <div class="swiper-slide">
                <img src="../static/img/entertainment.jpg">
                <a href="#" class="card_contents">
                  <div class="card_title">
                    오락
                  </div>
                  <div class="card_note">
                    놀이공원, 아쿠아리움 등 오락 시설을 중심으로 즐거움과 함께하는 여행
                    <span class="material-symbols-outlined arrow">arrow_right_alt</span>
                  </div>
                </a>
              </div>
              <div class="swiper-slide">
                <img src="../static/img/entertainment.jpg">
                <a href="#" class="card_contents">
                  <div class="card_title">
                    오락
                  </div>
                  <div class="card_note">
                    놀이공원, 아쿠아리움 등 오락 시설을 중심으로 즐거움과 함께하는 여행
                    <span class="material-symbols-outlined arrow">arrow_right_alt</span>
                  </div>
                </a>
              </div>
              <div class="swiper-slide">
                <img src="../static/img/entertainment.jpg">
                <a href="#" class="card_contents">
                  <div class="card_title">
                    오락
                  </div>
                  <div class="card_note">
                    놀이공원, 아쿠아리움 등 오락 시설을 중심으로 즐거움과 함께하는 여행
                    <span class="material-symbols-outlined arrow">arrow_right_alt</span>
                  </div>
                </a>
              </div>
              <div class="swiper-slide">
                <img src="../static/img/entertainment.jpg">
                <a href="#" class="card_contents">
                  <div class="card_title">
                    오락
                  </div>
                  <div class="card_note">
                    놀이공원, 아쿠아리움 등 오락 시설을 중심으로 즐거움과 함께하는 여행
                    <span class="material-symbols-outlined arrow">arrow_right_alt</span>
                  </div>
                </a>
              </div>
              <div class="swiper-slide">
                <img src="../static/img/entertainment.jpg">
                <a href="#" class="card_contents">
                  <div class="card_title">
                    오락
                  </div>
                  <div class="card_note">
                    놀이공원, 아쿠아리움 등 오락 시설을 중심으로 즐거움과 함께하는 여행
                    <span class="material-symbols-outlined arrow">arrow_right_alt</span>
                  </div>
                </a>
              </div>
            </div>
            <div class="swiper-pagination"></div>
          </div>
        </div>  
        <div class="festival_cont">
          <div class="cont_head">
            <h2>최근 축제 알아보기</h2>
            <p>최근 축제에 대해서 알아보고 참여해보세요.</p>
            <div class="festival_list">
              <div>
                <a href="{{ url_for('info.festival') }}" class="festival_img_wrap">
                  <img src="../static/img/winterfestival.png" alt="12월 겨울 축제">
                </a>
              </div>
            </div>
          </div>
        </div>
        <div class="popular_cont">
          <div class="cont_head">
            <h2>인기 여행지 알아보기</h2>
            <p>많은 사람들이 방문하는 여행지로 떠나보세요.</p>
          </div>
        </div>
      </div>
    </div>
    {% include 'config/footer.html' %}
  </div>
</body>
</html>